"""empty message

Revision ID: 1c1b5e492dc7
Revises: 939de71a4c1a
Create Date: 2026-04-01 18:27:41.322809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c1b5e492dc7'
down_revision = '939de71a4c1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identity_verification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_status', sa.Enum('pending', 'approved', 'rejected'), nullable=False))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=False))
        batch_op.drop_column('verifid_at')
        batch_op.drop_column('verificaticon_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identity_verification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verificaticon_status', mysql.ENUM('pending', 'approved', 'rejected'), server_default=sa.text("'pending'"), nullable=False))
        batch_op.add_column(sa.Column('verifid_at', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False))
        batch_op.drop_column('verified_at')
        batch_op.drop_column('verification_status')

    # ### end Alembic commands ###
