"""empty message

Revision ID: 2821875d8e32
Revises: f6a52f31ed8c
Create Date: 2026-09-23 13:04:36.987745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2821875d8e32'
down_revision = 'f6a52f31ed8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_submissions',
    sa.Column('submission_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('landlord_name', sa.String(length=150), nullable=False),
    sa.Column('landlord_email', sa.String(length=255), nullable=False),
    sa.Column('landlord_phone', sa.String(length=30), nullable=False),
    sa.Column('property_title', sa.String(length=300), nullable=False),
    sa.Column('property_type', sa.Enum('land', 'house', 'apartment', 'commercial'), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('submission_status', sa.Enum('pending', 'approved', 'rejected'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_table('property_submission_images',
    sa.Column('image_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['property_submissions.submission_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    with op.batch_alter_table('property_submission_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_submission_images_submission_id'), ['submission_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_submission_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_submission_images_submission_id'))

    op.drop_table('property_submission_images')
    op.drop_table('property_submissions')
    # ### end Alembic commands ###
