"""empty message

Revision ID: 58510fa7dbdd
Revises: 26ed975180da
Create Date: 2026-09-24 01:09:21.438727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58510fa7dbdd'
down_revision = '26ed975180da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by_admin_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('published_property_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_property_submissions_published_property_id'), ['published_property_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_property_submissions_reviewed_by_admin_id'), ['reviewed_by_admin_id'], unique=False)
        batch_op.create_foreign_key(None, 'properties', ['published_property_id'], ['property_id'])
        batch_op.create_foreign_key(None, 'admin', ['reviewed_by_admin_id'], ['admin_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_submissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_property_submissions_reviewed_by_admin_id'))
        batch_op.drop_index(batch_op.f('ix_property_submissions_published_property_id'))
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('published_property_id')
        batch_op.drop_column('reviewed_by_admin_id')
        batch_op.drop_column('reviewed_at')

    # ### end Alembic commands ###
