"""empty message

Revision ID: 5c98307573d8
Revises: 58510fa7dbdd
Create Date: 2026-09-24 15:41:45.217430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c98307573d8'
down_revision = '58510fa7dbdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('archive_reason', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('archive_note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('archive_note')
        batch_op.drop_column('archive_reason')
        batch_op.drop_column('archived_at')

    # ### end Alembic commands ###
