"""make property owner nullable

Revision ID: 5ef4b41c11a3
Revises: 1c1b5e492dc7
Create Date: 2026-09-18 02:37:31.489934

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ef4b41c11a3'
down_revision = '1c1b5e492dc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
