"""empty message

Revision ID: 939de71a4c1a
Revises: 
Create Date: 2026-03-17 01:04:33.998731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '939de71a4c1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'state', ['state_id'], ['state_id'])

    with op.batch_alter_table('property_agents', schema=None) as batch_op:
        batch_op.alter_column('agency_status',
               existing_type=mysql.ENUM('pending', 'active', 'suspended'),
               type_=sa.Enum('active', 'suspended', 'pending'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_agents', schema=None) as batch_op:
        batch_op.alter_column('agency_status',
               existing_type=sa.Enum('active', 'suspended', 'pending'),
               type_=mysql.ENUM('pending', 'active', 'suspended'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('state_id')

    # ### end Alembic commands ###
