"""empty message

Revision ID: be641c6ff835
Revises: 2821875d8e32
Create Date: 2026-09-23 17:29:35.657536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be641c6ff835'
down_revision = '2821875d8e32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listing_type', sa.Enum('sale', 'rent'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_submissions', schema=None) as batch_op:
        batch_op.drop_column('listing_type')

    # ### end Alembic commands ###
