"""empty message

Revision ID: cf6c267ed5f6
Revises: 5ef4b41c11a3
Create Date: 2026-09-18 02:58:39.886224

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf6c267ed5f6'
down_revision = '5ef4b41c11a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
       
    # ### end Alembic commands ###
