"""empty message

Revision ID: f6a52f31ed8c
Revises: cf6c267ed5f6
Create Date: 2026-09-18 23:49:30.071466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a52f31ed8c'
down_revision = 'cf6c267ed5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_primary', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_image', schema=None) as batch_op:
        batch_op.drop_column('is_primary')

    # ### end Alembic commands ###
